name: Create release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-zip-upload:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: "webpack-loader-sass-glob-import"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.0.0

      - run: npm ci
      - run: npm test

      - name: Zip release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          filename: "${{ env.RELEASE_NAME }}.zip"
          path: "LICENSE dist/ package.json README.md"

      # Publish the release
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.RELEASE_NAME }}.zip"
          generateReleaseNotes: true